on:
  workflow_dispatch:
  push:
    branches: [master]

name: Publish to Github Container Registry

jobs:
  publish:
    name: Publish Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node Environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '>=15.8.0'
        
    - name: Configure Cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
        
    - name: Install npm packages
      run: npm install
      
    - name: Build application
      run: npm runx nx build
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        
    - name: Build Image
      run: docker build -t bugoeste-hub .
      
    - name: Push image
      run: docker image push bugoeste-hub
    
