on:
  workflow_dispatch:
  push:
    branches: [master]

name: Publish to Github Container Registry

jobs:
  publish:
    name: Publish Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '>=15.8.0'

      - name: Restore cached node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install npm packages
        run: npm install

      - name: Build application
        run: npm run nx build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Restore docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build Image
        run: docker build -t bugoeste-hub .

      - name: Push image
        run: |
          docker image tag bugoeste-hub ghcr.io/${{ github.repository_owner }}/bugoeste-hub
          docker image push 'ghcr.io/${{ github.repository_owner }}/bugoeste-hub:latest'

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          fingerprint: ${{ secrets.HOST_SSH_FINGERPRINT }}
          script: |
            cd ${{ secrets.BUGOESTE_HUB_COMPOSE_LOCATION }}
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            ${{ secrets.DOCKER_COMPOSE_BIN }} restart
